### ISSUE TITLE
AMust ndn build failed

### ISSUE THREAD

**Issue by 123aya123** [ChristianKreuzberger/AMuSt-ndnSIM#3]
Hello
i am trying to install Amust ndn framework on my machine (ubuntu16.4.0) i  have configuration finished successfully but build failed and give the following error 
In file included from ./ns3/trace-source-accessor.h:24:0,
                 from ./ns3/type-id.h:25,
                 from ./ns3/object-base.h:23,
                 from ./ns3/object.h:29,
                 from ./ns3/object-factory.h:24,
                 from ./ns3/simulator.h:29,
                 from ./ns3/ndnSIM/model/ndn-common.hpp:24,
                 from ../src/ndnSIM/utils/tracers/ndn-l3-tracer.hpp:23,
                 from ../src/ndnSIM/utils/tracers/ndn-l3-tracer.cpp:20:
./ns3/callback.h: In instantiation of ‘static std::__cxx11::string ns3::CallbackImplBase::GetCppTypeid() [with T = const nfd::pit::Entry&; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
./ns3/callback.h:233:24:   required from ‘static std::__cxx11::string ns3::CallbackImpl<R, T1, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty>::DoGetTypeid() [with R = void; T1 = const nfd::pit::Entry&; std::__cxx11::string = std::__cxx11::basic_string<char>]’
./ns3/callback.h:226:24:   required from ‘std::__cxx11::string ns3::CallbackImpl<R, T1, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty>::GetTypeid() const [with R = void; T1 = const nfd::pit::Entry&; std::__cxx11::string = std::__cxx11::basic_string<char>]’
../src/ndnSIM/utils/tracers/ndn-l3-tracer.cpp:74:1:   required from here
./ns3/callback.h:175:36: error: invalid use of incomplete type ‘class nfd::pit::Entry’
         typeName = typeid (T).name ();
                    ~~~~~~~~~~~~~~~~^~
In file included from ../src/ndnSIM/utils/tracers/ndn-l3-tracer.cpp:20:0:
../src/ndnSIM/utils/tracers/ndn-l3-tracer.hpp:31:7: note: forward declaration of ‘class nfd::pit::Entry’
 class Entry;
       ^~~~~
Waf: Leaving directory `/home/aya/Desktop/AmustndnSIM/ns-3/build'

Build failed
 -> task in 'ns3-ndnSIM' failed (exit status 1): 
	{task 140421141580944: cxx ndn-l3-tracer.cpp -> ndn-l3-tracer.cpp.3.o}
['/usr/bin/g++', '-std=c++0x', '-std=c++11', '-O0', '-ggdb', '-g3', '-Wall', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-std=c++11', '-fPIC', '-pthread', '-I.', '-I..', '-Ins3/ndnSIM/NFD', '-I../ns3/ndnSIM/NFD', '-Isrc/ndnSIM/NFD/core', '-I../src/ndnSIM/NFD/core', '-Isrc/ndnSIM/NFD/daemon', '-I../src/ndnSIM/NFD/daemon', '-Isrc/ndnSIM/NFD/rib', '-I../src/ndnSIM/NFD/rib', '-Ins3/ndnSIM', '-I../ns3/ndnSIM', '-Ins3/ndnSIM/ndn-cxx', '-I../ns3/ndnSIM/ndn-cxx', '-I/home/aya/ndnSIM/BRITE', '-I.', '-I..', '-I/usr/include/libxml2', '-I/usr/include', '-I/home/aya/ndnSIM/AMuSt-libdash/libdash/libdash/include', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IS_DEFAULT_CONSTRUCTIBLE=1', '-DHAVE_IS_NOTHROW_MOVE_CONSTRUCTIBLE=1', '-DHAVE_IS_NOTHROW_MOVE_ASSIGNABLE=1', '-DHAVE_CXX_FRIEND_TYPENAME=1', '-DHAVE_CXX_OVERRIDE_FINAL=1', '-DNDN_CXX_HAVE_VECTOR_INSERT_ERASE_CONST_ITERATOR=1', '-DHAVE_PTHREAD=1', '-DHAVE_SQLITE3=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_LIBXML2=1', '../src/ndnSIM/utils/tracers/ndn-l3-tracer.cpp', '-c', '-o', '/home/aya/ndnSIM/ns-3/build/src/ndnSIM/utils/tracers/ndn-l3-tracer.cpp.3.o']

any help to solve this problem
thanks in advance

**Comment by bekiroguzhan** [comment]
I am having the same issue. If anyone knows how to resolve, that would be appreciated.
